/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dbconn.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author eabr1
 */
public class Cafeterias extends javax.swing.JFrame {

    /**
     * Creates new form Cafeterias
     */
    public Cafeterias() {
        initComponents();
        llenarComboBox1();
        llenarComboBox2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbHabilitado = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbCampus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtEncargado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbCafeteria = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbHabilitado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbHabilitado.setText("Habilitado");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cafeterias");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Descripción:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Campus:");

        cbCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Encargado:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cafeteria:");

        cbCafeteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion)
                            .addComponent(cbCampus, 0, 198, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbHabilitado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbCafeteria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCafeteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHabilitado)
                    .addComponent(jButton1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cbCafeteria.getSelectedIndex();

        if(selectedIndex == -1){
            JOptionPane.showMessageDialog(Cafeterias.this, "Debe seleccionar un elemento.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //        else if(contrasenaUsuario == null || contrasenaUsuario.length() == 0){
            //            JOptionPane.showMessageDialog(UsuariosTipos.this, "El campo Clave no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
            //        }
        //
        //        else if(contrasenaUsuario2 == null || contrasenaUsuario2.length() == 0){
            //            JOptionPane.showMessageDialog(UsuariosTipos.this, "El campo Confirmar no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
            //        }
        //
        //        else if(!contrasenaUsuario.equals(contrasenaUsuario2)){
            //            JOptionPane.showMessageDialog(UsuariosTipos.this, "Las claves no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);
            //        }
        else{
            Object selectedItem = cbCafeteria.getSelectedItem();

            String nombreUsuario = selectedItem.toString();
            try {
                // Obtener una conexión de la base de datos
                Connection conexion = ConexionBD.obtenerConexion();

                // Consulta SQL para verificar el inicio de sesión
                String consulta = "DELETE FROM ISO610.Cafeteria Where descripcion = ?";
                PreparedStatement preparedStatement = conexion.prepareStatement(consulta);
                preparedStatement.setString(1, nombreUsuario);

                int filasInsertadas = preparedStatement.executeUpdate();

                JOptionPane.showMessageDialog(Cafeterias.this, "Cafeteria eliminado correctamente.", "Completado", JOptionPane.INFORMATION_MESSAGE);
                limpiarCombobox();
                llenarComboBox1();                
                llenarComboBox2();


                // Cerrar recursos
                preparedStatement.close();
                ConexionBD.cerrarConexion(conexion);

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String descrip = txtDescripcion.getText();        
        String Encar = txtEncargado.getText();

        int selectedIndex = cbCampus.getSelectedIndex();
        
        if(descrip == null || descrip.length() == 0){
            JOptionPane.showMessageDialog(Cafeterias.this, "El campo Descripción no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (selectedIndex == -1)
            JOptionPane.showMessageDialog(Cafeterias.this, "El campo Campus no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
        else if(Encar == null || Encar.length() == 0){
            JOptionPane.showMessageDialog(Cafeterias.this, "El campo Encargado no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int Habilitado = 0;
            
            if(cbHabilitado.isSelected()){
                Habilitado = 1;
            }
            
            try {
                
                Object selectedItem = cbCampus.getSelectedItem();

                    String Campus = selectedItem.toString();

                // Obtener una conexión de la base de datos
                Connection conexion = ConexionBD.obtenerConexion();

                // Consulta SQL para verificar el inicio de sesión
                String consulta = "IF NOT EXISTS (SELECT TOP 1 1 FROM iso610.Cafeteria WHERE Descripcion = ? ) BEGIN INSERT INTO iso610.Cafeteria (Descripcion, IdCampus,Encargado,Estado) VALUES (?,(select idcampus FROM ISO610.Campus Where descripcion = ?),?,?) END";
                PreparedStatement preparedStatement = conexion.prepareStatement(consulta);
                preparedStatement.setString(1, descrip);                
                preparedStatement.setString(2, descrip);                
                preparedStatement.setString(3, Campus);
                preparedStatement.setString(4, Encar);
                preparedStatement.setInt(5, Habilitado);
 

                int filasInsertadas = preparedStatement.executeUpdate();
                
                JOptionPane.showMessageDialog(Cafeterias.this, "Cafeteria agregada correctamente.", "Completado", JOptionPane.INFORMATION_MESSAGE);
                limpiarCombobox();
                llenarComboBox1();
                llenarComboBox2();

                
                // Cerrar recursos
                preparedStatement.close();
                ConexionBD.cerrarConexion(conexion);
                
                
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafeterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafeterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafeterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafeterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafeterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbCafeteria;
    private javax.swing.JComboBox<String> cbCampus;
    private javax.swing.JCheckBox cbHabilitado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEncargado;
    // End of variables declaration//GEN-END:variables

    private void llenarComboBox1() {
        ArrayList<String> elementos = new ArrayList<>();
        try {
            
            Connection conexion = ConexionBD.obtenerConexion();

            // Crear y ejecutar la consulta SQL para obtener id y descripción
            String consultaSQL = "SELECT DESCRIPCION FROM [dbApec].[iso610].Campus";
            PreparedStatement statement = conexion.prepareStatement(consultaSQL);
            ResultSet resultSet = statement.executeQuery();

            // Crear objetos ComboBoxItem y agregarlos al JComboBox
            while (resultSet.next()) {
                String elemento = resultSet.getString("DESCRIPCION");
                elementos.add(elemento);
            }

            // Cerrar la conexión y los recursos
            resultSet.close();
            statement.close();
            conexion.close();
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(elementos.toArray(new String[0]));
            cbCampus.setModel(model);
            cbCampus.setSelectedIndex(-1);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void limpiarCombobox() {
        cbCafeteria.removeAllItems();
        cbCampus.removeAllItems();
        txtEncargado.setText("");
        txtDescripcion.setText("");
        cbHabilitado.setSelected(false); 
    }

    private void llenarComboBox2() {
        ArrayList<String> elementos = new ArrayList<>();
        try {
            
            Connection conexion = ConexionBD.obtenerConexion();

            // Crear y ejecutar la consulta SQL para obtener id y descripción
            String consultaSQL = "SELECT DESCRIPCION FROM [dbApec].[iso610].Cafeteria";
            PreparedStatement statement = conexion.prepareStatement(consultaSQL);
            ResultSet resultSet = statement.executeQuery();

            // Crear objetos ComboBoxItem y agregarlos al JComboBox
            while (resultSet.next()) {
                String elemento = resultSet.getString("DESCRIPCION");
                elementos.add(elemento);
            }

            // Cerrar la conexión y los recursos
            resultSet.close();
            statement.close();
            conexion.close();
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(elementos.toArray(new String[0]));
            cbCafeteria.setModel(model);
            cbCafeteria.setSelectedIndex(-1);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
